VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITester"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("SurveyMerge.Tests")
' class module: ITester
'
Option Explicit

Public Property Get className() As String
End Property

Public Property Get testList() As Variant
End Property

Public Function runTest(ByRef methodName As String) As Boolean
End Function

Public Sub setUp()
End Sub

Public Sub breakDown()
End Sub
