VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrinter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("SurveyMerge.Views")
'
' class module: IPrinter
'
Option Explicit

Public Sub printData(ByVal surveyRun As ModelSurveyRun, ByVal lineNo As Long)

End Sub

Public Sub printError(ByVal description As String, ByVal lineNo As Long)

End Sub

