VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrinter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'
' class module: IPrinter
'
Option Explicit

Public Sub printData(surveyRun As ModelSurveyRun, lineNo As Integer)

End Sub

Public Sub printError(descriptions As String, lineNo As Integer)

End Sub
