VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrinter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("SurveyMerge.Utilities")
'
' class module: IPrinter
'
Option Explicit

Public Sub printData(ByRef surveyRun As ModelSurveyRun, ByRef lineNo As Long)

End Sub

Public Sub printError(ByVal descriptions As String, ByVal lineNo As Long)

End Sub

