VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ModelSurveyRun"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("SurveyMerge.Model")
'
' class module: ModelSurveyRun
'
Option Explicit

Public questionCount As Long
Public surveyName As String
Public participantId As String
Public startTime As Date
Public endTime As Date
Public answerCollection As Answers





